### ISSUE TITLE
Add joystick button functions for relays 3 and 4

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#102]
Currently we have 4 relay objects, but only allow access to 2 via the joystick buttons.

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/ardusub/blob/master/ArduSub/joystick.cpp#L330

**Comment by dheideman** [comment]
See [pr-relay-btn-functions](https://github.com/bluerobotics/ardusub/tree/pr-relay-btn-functions)

**Comment by jaxxzer** [comment]
@dheideman You need to split this into two commits, first AP_Param, then ArduSub. Take care to only commit changes in one directory at a time.

**Comment by dheideman** [comment]
@jaxxzer Split.

**Comment by jaxxzer** [comment]
Merged, thanks.
