### ISSUE TITLE
GPS Detected as MAV...

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#104]
This is basically the only GPS type we can practically use. It would be nice to just set this up as the default value.

However, this message prints out about ~0.5Hz as the driver constantly restarts when there is no data. And the majority of users will have no data... Make the driver start once, then just wait, so that the message is only printed once.

**Comment by patrickelectric** [comment]
How can I reproduce this ?

**Comment by jaxxzer** [comment]
Set the GPS_TYPE parameter as 'MAV' and reboot. It will stop when gps connects.
