### ISSUE TITLE
Announce different message on input hold disabled

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/ardusub#108]
Don't announce "Input Hold Set" when pressing input hold set button disables input hold.  Announce "Input Hold Disabled" instead.

**Comment by dheideman** [comment]
[pr-input-hold-announcements](https://github.com/bluerobotics/ardusub/tree/pr-input-hold-announcements)

**Comment by rjehangir** [comment]
Make sure that if you press it in the center a few times it doesn't do anything since the input hold will still be disabled.

**Comment by dheideman** [comment]
Good idea.  That functionality has been added.

**Comment by jaxxzer** [comment]
merged
