### ISSUE TITLE
Don't allow other functions to output to channels with motor assignment.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#110]
Retrofitting existing BROV2 with 8 thrusters causes conflict on output 7 between lights output and motor output.

**Comment by jaxxzer** [comment]
Fixed for 3.5 here: https://github.com/ArduPilot/ardupilot/commit/2e8d50e8e4861b1653d9fce373bdd5495d673647

This has already been resolved in master.

**Comment by suarez-ramon** [comment]
Hello, I think we are having a problem with this. We have a custom AUV with 8 motors. All the motors work correctly except for motor 7. It starts to twitch and others move. Is this a problem similar to yours? I have checked in the master branch and the changes you mention here: ArduPilot/ardupilot@2e8d50e are not there.

Thanks!
