### ISSUE TITLE
Don't require SD card to run.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#112]
Don't bail at boot if there is no SD card present.

**Comment by jaxxzer** [comment]
Bail at boot with no SD only happens if USB is connected.

Behavior is controlled in init script here https://github.com/ArduPilot/ardupilot/blob/master/mk/PX4/ROMFS/init.d/rcS

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
