### ISSUE TITLE
SERVO_OUTPUT_RAW > 8 are not available via mavlink

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#113]
Setting serial protocol to mavlink 2 does not change anything here.

**Comment by patrickelectric** [comment]
@jaxxzer is was necessary to change the ArduSub channel 0 to SerialProtocol_MAVLink2.
But the doc say:
- `SerialProtocol_MAVLink2 = 2,                 // do not use - use MAVLink and provide instance of 1`

Any idea why this change is necessary ?
I have all SERIALX_PROTOCOLS in MAVLink2

### Checking the problem: ###
```
mavlink_status_t *status = mavlink_get_channel_status(chan);
// If mavlink1 is True, it'll be used mavlinkV1.
bool mavlink1 = (status->flags & MAVLINK_STATUS_FLAG_OUT_MAVLINK1) != 0;
```

### How to fix: ###
Change [ArduSub/system.cpp#L59](https://github.com/bluerobotics/ardusub/blob/master/ArduSub/system.cpp#L59) to use `SerialProtocol_MAVLink2`.

**Comment by patrickelectric** [comment]
Add mavlink issue: mavlink/mavlink/issues/803

**Comment by patrickelectric** [comment]
@jaxxzer I just tested the last version of ardusub and our QGC release, everything is working fine. :shipit:

**Comment by jaxxzer** [comment]
What version of ardusub, what SERIAL settings? I am unable to get the numbers out.

**Comment by patrickelectric** [comment]
Check the video here:
https://transfer.sh/NbRLz/deepin-screen-recorder_Select%20area_20180611175850.mp4
Serial settings:
![screenshot from 2018-06-11 18-03-24](https://user-images.githubusercontent.com/1215497/41257197-5b63c220-6da2-11e8-8aae-8fe462321201.png)

You need to set mavproxy to use mavlink 2 with `--mav20`

**Comment by patrickelectric** [comment]
Check here: https://github.com/bluerobotics/companion/pull/129

**Comment by jaxxzer** [comment]
I'm not using mavproxy, I'm connected directly by usb. What's my problem then?

**Comment by patrickelectric** [comment]
If you did configure the serial port to output mavlink2, we should talk with gus and don about it.

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
