### ISSUE TITLE
Joystick button press to pulse servo output channel

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/ardusub#126]
When controlling a manipulator it's necessary to briefly send a signal pulse to a servo channel. We need a user-configurable "speed" and then button assignments to pulse at that speed when the button is pressed. If the button is held then the signal should be output until it is released. If we also add a toggle on/off function, then this can support other devices that are meant to run constantly, like a pump motor.

Forum requests:

([Forum 1](http://discuss.bluerobotics.com/t/two-electronics-packages-on-one-tether/1757))

([Forum 2](http://discuss.bluerobotics.com/t/optional-tooling-for-blue2/1298/4))

**Comment by jaxxzer** [comment]
Done!
