### ISSUE TITLE
Add option to set system time via GCS

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#131]
Perhaps by emitting SYSTEM_TIME message from GCS.

**Comment by patrickelectric** [comment]
https://github.com/ArduPilot/ardupilot/pull/8121 Will do the job.

**Comment by jaxxzer** [comment]
will that be easily rebased onto Sub-3.5?

**Comment by patrickelectric** [comment]
If not, we can merge the original PR.

**Comment by jaxxzer** [comment]
I agree

**Comment by jaxxzer** [comment]
Done!
