### ISSUE TITLE
Acro yaw does not work correctly

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#154]
As roll/pitch approach +/-90 degrees, the yaw controller output approaches zero. These values should be independent of each other.

To test: set ACRO_TRAINER to disabled.

https://discuss.bluerobotics.com/t/acro-mode-and-yaw-rate-commands/2491/10

**Comment by maxdrougge** [comment]
Hi. How is a fix for this coming along?

**Comment by jaxxzer** [comment]
There has been no progress.

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
