### ISSUE TITLE
Dependency installer script misses some dependencies.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#155]
The script in question: https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/install-prereqs-ubuntu.sh

It is missing:
cmake
future (pip)
python-empy
genromfs
Mavproxy (pip)

**Comment by mariyachanniwala** [comment]
The install pre req file already has all the dependencies written into it. Still its not installing a few of them. Need to check why.
