### ISSUE TITLE
Arming check parameter does not save

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#20]
No matter what ARMING_CHECK is set to, it always says enabled in qgc. SAFETY_ENABLE behaves as expected.

**Comment by jaxxzer** [comment]
This appears to be an issue with qgc. Parameter changes are retained appropriately except for arming_check. The same behavior is observed running Copter 3.3.3

**Comment by rjehangir** [comment]
We likely have an error in the parameter description that is processed into QGC then. I'll look into it.

**Comment by jaxxzer** [comment]
Copter is doing the same thing!

**Comment by rjehangir** [comment]
Okay. I think it's a QGC thing. Params in ArduSub look good.

I would recommend opening an issue for QGC.

**Comment by jaxxzer** [comment]
Will do.

**Comment by rjehangir** [comment]
This has been fixed in the QGC master.
