### ISSUE TITLE
qGround Control crashes 100% under Windows 10

### ISSUE THREAD

**Issue by marinesimulation** [bluerobotics/ardusub#56]
#### Issue details
qGroundControl crashes during closing when running under Windows 10.  This is 100% reproducible and qGroundControl crashes 100% of the time.  To reproduce, install and run qGC on a Windows 10 computer.  Operate as normal.  Click on close (red "x" button of window).  Click on "Yes" when asked to close open connections.  At this point the application crashes.  Sometimes it opens the "save file" dialog box and then crashes when you select "Cancel" and sometimes it crashes while the dialog box is open (as in the screen shot below).  But it crashes 100% of the time.
![img_20161209_141030129](https://cloud.githubusercontent.com/assets/17232608/21061690/62ab134a-be1b-11e6-8d00-1d2f8e305999.jpg)
![img_20161209_141204681_hdr](https://cloud.githubusercontent.com/assets/17232608/21061689/62ab102a-be1b-11e6-93f7-3094ff29c2fc.jpg)
![img_20161209_141222473_hdr](https://cloud.githubusercontent.com/assets/17232608/21061691/62ab9d60-be1b-11e6-8023-503cb8f82fd0.jpg)

#### Version
QGroundControl Development HEAD:23d3eb5 2016-12-07 17:38:58 -0800

#### Platform
BlueROV2 Vectored Thrust

#### Airframe type
Sub

#### Hardware type
Pixhawk, Raspberry Pi, Fathom-X, Dell i7 laptop, Windows 10

**Comment by marinesimulation** [comment]
I may have found a work-around:

I first turned off "prompt to save flight data" in the qGC options.
Now before I close qGC I disconnect my laptop from the network first (removing power from the topside Fathom-X board).

I've tested this twice and both times qGC closed without issues.

**Comment by rjehangir** [comment]
Addressed in https://github.com/mavlink/qgroundcontrol/pull/4315
