### ISSUE TITLE
Intermittent "lost communication" error

### ISSUE THREAD

**Issue by marinesimulation** [bluerobotics/ardusub#58]
#### Issue details
Topside running qGround Control looses communications with the ROV side.

#### Version
2.0rc1

#### Platform
Sub/BlueROV2

#### Airframe type
Vectored Thrust

#### Hardware type
Windows 10 laptop, Fathom-X, Pixhawk

#### Logs
qGround Control looses communications with the ROV and reports "communications lost".  Then after several seconds it connects and reports "communications regained".  I've had this happen twice in less than 10 minutes.  The ROV is not moving and nothing is being touched or moved (which might indicate a loose connection.

**Comment by jaxxzer** [comment]
This happens when QGC does not see a heartbeat for 3 seconds. In the months that have passed since this was submitted, I have not seen this happen in any unexpected situation. There are a number of possible causes for this that are outside the scope of ArduSub.
