### ISSUE TITLE
Auto-config motor directions

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#78]
Consider adding a function that will run each thruster individually and determine the correct value for the corresponding MOT_N_DIRECTION parameter. (Must be performed in water).

In order to do this, each motor must have some contribution to rotational movement, or depth movement, as we cannot measure forward/lateral movement alone without extra hardware.

Maybe a MAV_CMD to initiate?

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/ardusub/commits/pr-motor-auto-config

**Comment by jaxxzer** [comment]
> In order to do this, each motor must have some contribution to rotational movement, or depth movement, as we cannot measure forward/lateral movement alone without extra hardware.

It might be very well doable to look at the accelerometers to figure out straight forward/lateral configurations.

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
