### ISSUE TITLE
Translate roll/pitch to strafe/forward in position control.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#8]
ROVs have direct control over linear control in the xy plane with no requirement of pitch and roll to achieve target position. Translate/redirect pitch/roll commands from position controller to forward/strafe commands to move to target.

**Comment by jaxxzer** [comment]
This has been implemented in the Poshold-nogps branch. https://github.com/bluerobotics/ardusub/blob/Poshold-NoGPS/ArduSub/control_poshold.cpp

**Comment by rjehangir** [comment]
@jaxxzer - think we can close this issue?

**Comment by jaxxzer** [comment]
Yep!
