### ISSUE TITLE
Dont allow positive depth readings.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#82]
Suggest recalibrating the depth sensor if we are reading positive depth.

**Comment by rjehangir** [comment]
Maybe we should have a threshold for this, like if we are reading > 0.5m above the surface. Also, might want to have it check this for a few seconds because a rapid ascent or shock to the accelerometers could cause the Kalman filter to register higher briefly. Thoughts?

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
