### ISSUE TITLE
Ardusub "Waiting for vehicle connection"

### ISSUE THREAD

**Issue by giligan13** [bluerobotics/ardusub#88]
#### Issue details
_Please describe the problem, or desired feature_
Brand new BlueROV2.  Installed Q Ground Control on laptop.  Attempting to continue with Ardusub installation.  Laptop IP set to 192.168.2.1.  Able to ping 192.168.2.2(Pixhawk?).  Q Ground Control unable to start firmware upgrade.  "Waiting for Vehicle Connection" displayed on laptop.  Pixhawk displays blinking Blue ACT LED, blinking large yellow unknown LED, and solid yellow PWR LED.  What have I missed?

#### Version
_What version was the issue encountered with_UNKOWN version

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[ x ] Rover

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by jaxxzer** [comment]
Hi Giligan, please comment on the Blue Robotics Forums, or email support@bluerobotics.com for help with your ROV. This space is for feature requests/bug reports in the code.

It sounds like you have a firewall blocking incoming connections, or you have not allowed the QGroundControl app access through the firewall. No firmware upgrade is necessary on your BROV2.
