### ISSUE TITLE
Auto-document DataFlash messages

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#89]
like parameters.

**Comment by jaxxzer** [comment]
Upstream issue: https://github.com/ArduPilot/ardupilot/issues/5864

I consider this a priority, so leaving the issue here open.

Ping @patrickelectric if you are interested in a fun night on this (:, I'm sure it will be a popular effort among the ardupilot crowd.

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
