### ISSUE TITLE
Add current draw to simulation

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#94]
Maybe options like proportional/quadratic relationship to pwm output.

**Comment by jaxxzer** [comment]
See https://github.com/bluerobotics/ardusub/tree/sub-current-monitor-sim

**Comment by jaxxzer** [comment]
https://github.com/ArduPilot/ardupilot/pull/7140

**Comment by patrickelectric** [comment]
@jaxxzer can we close this ?

**Comment by jaxxzer** [comment]
Yes!
