### ISSUE TITLE
Add support for TSYS01 on pixhawk 2

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ardusub#97]
The bus is hard coded, it needs to be determined at run time.

**Comment by proficnc** [comment]
CSB=1 the address is 1110110x.
CSB=0 the address is 1110111x. 
so in theory, you should be able to put 4 of these on a PH2

**Comment by proficnc** [comment]
"When I change the board type to Pixhawk 1, everything works fine, when it is on Pixhawk 2, the temp mirrors the board temperature "

**Comment by patrickelectric** [comment]
Moved to ArduPilot.
